# Generated by Django 3.0.7 on 2020-06-13 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20200613_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Preferences',
            name='selected_colorset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='chat.Colorset'),
        ),
    ]
