# Generated by Django 3.0.7 on 2020-06-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20200613_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='Preferences',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
