# Generated by Django 3.0.7 on 2020-06-17 11:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0008_preferences_is_online'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preferences',
            new_name='Profile',
        ),
    ]
