# Generated by Django 3.0.7 on 2020-06-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20200617_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_system_message',
            field=models.BooleanField(default=False),
        ),
    ]
