# Generated by Django 3.0.7 on 2020-06-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_message_is_system_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='just_left',
            field=models.BooleanField(default=False),
        ),
    ]
