# Generated by Django 3.0.7 on 2020-06-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_profile_just_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_server_message',
            field=models.BooleanField(default=False),
        ),
    ]
