# Generated by Django 3.0.7 on 2020-06-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20200623_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='room',
            name='user_1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='user_2',
        ),
    ]
