# Generated by Django 3.0.7 on 2020-06-23 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_auto_20200623_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_public',
        ),
    ]
