# Generated by Django 3.0.7 on 2020-06-23 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_auto_20200623_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='user_2',
        ),
    ]
