# Generated by Django 3.0.7 on 2020-06-23 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_remove_room_user_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='user_1',
        ),
    ]
