# Generated by Django 3.0.7 on 2020-06-23 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0028_room_user_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='in_room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.Room'),
        ),
    ]
