# Generated by Django 3.0.7 on 2020-07-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0032_attachment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='%Y/%m/%d/'),
        ),
    ]
