# Generated by Django 3.0.7 on 2020-07-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0033_auto_20200711_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='dispatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
