# Generated by Django 3.0.7 on 2020-07-15 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0036_auto_20200715_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selected_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='chat.Language'),
        ),
    ]
