# Generated by Django 3.0.7 on 2020-07-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0037_profile_selected_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_muted',
            field=models.BooleanField(default=False),
        ),
    ]
