# Generated by Django 3.0.7 on 2020-07-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0038_profile_is_muted'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sound_notification_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
